# Generated by Django 5.0.4 on 2024-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cateogory',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_count',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='on_site_only',
        ),
        migrations.AddField(
            model_name='equipment',
            name='audit_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='comments',
            field=models.CharField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='equipment',
            name='img_url',
            field=models.CharField(default='base/westminster-logo.png', max_length=254),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='Other', max_length=254),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='borrow_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(default='Other', max_length=254),
        ),
    ]
