# Generated by Django 5.0.4 on 2024-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_equipment_cateogory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
