# Generated by Django 5.0.4 on 2024-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_equipment_quantity_equipment_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='123password', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123password', max_length=150),
        ),
    ]
