# Generated by Django 4.2.11 on 2024-04-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogory', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('equipment_count', models.IntegerField(default=0)),
                ('equipment_type', models.CharField(max_length=254)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('on_site_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('role_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_duration', models.DurationField()),
                ('approval_status', models.BooleanField(default=False)),
                ('cancellation', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(max_length=254)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.admin')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='availability',
            field=models.ManyToManyField(blank=True, related_name='reserved_equipment', to='base.user'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('return_date', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.admin')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='approval_status',
            field=models.ManyToManyField(blank=True, related_name='managed_approval_status', to='base.user'),
        ),
        migrations.AddField(
            model_name='admin',
            name='booking_approval',
            field=models.ManyToManyField(blank=True, related_name='confirmed_by_admin', to='base.booking'),
        ),
        migrations.AddField(
            model_name='admin',
            name='equipment_manage',
            field=models.ManyToManyField(blank=True, related_name='managed_equipment', to='base.equipment'),
        ),
        migrations.AddField(
            model_name='admin',
            name='reservation_approval',
            field=models.ManyToManyField(blank=True, related_name='approved_by_admin', to='base.reservation'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='admin',
            name='users_manage',
            field=models.ManyToManyField(blank=True, related_name='managed_users', to='base.user'),
        ),
    ]
